language: java
jdk:
    - openjdk8
cache:
  directories:
  - .autoconf
  - $HOME/.m2
addons:
  sonarcloud:
    organization: "tharindu-bandara" # the key of the org you chose at step #3
script:
  - mvn clean install
  - sonar-scanner
